---
title: "Replication of Study 1 by Mani, Mullainathan, Shafir, & Zhao (2013, Science)"
author: "Vivian Huynh (vivhuynh@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

<!-- [No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information.  It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  -->

In the original study "Poverty Impedes Cognitive Function," by Mani, Mullainathan, Shafir, and Zhao, researchers hypothesized that poverty has a direct effect on cognitive functions and conducted two studies to test their hypothesis. In these studies, it was evident that the cognitive capacities of low-income participants as opposed to high-income participants varied significantly when affected by financial situations. Researchers also examined farmers during harvesting season to test their cognitive function before they were paid and were temporarily "poor," and after they were paid. Mani, Mullainathan, Shafir, and Zhao claim that poverty itself "reduces cognitive capacity," as a result of the financial stress that consumes cognitive resources, which further perpetuates poverty in the poor--financially, mentally, and behaviorally. 

As an undergraduate in Symbolic Systems with a concentration in Cognitive Science, the idea of limited cognition as a result of poverty interests me because of the intersectionality of being a first generation, low-income student that studies the brain. Upon reading this article, skepticism definitely arose because being low-income or growing up in poverty does not necessarily imply that people in these circumstances will be less successful, however, there is truth and evidence that demonstrates how poverty structurally--and even generationally--affects the cognition in those living in poverty. There are many factors that impact low-income populations aside from finances, and this article provides evidence of the behaviors and thought processes as a result of limited cognition from poverty itself.

To replicate this experiment, we will conduct two studies: the first study will randomly assign low-income and high-income participants to an easy condition or hard condition, with the conditions varying from a low cost or high cost hypothetical financial scenario. We will be using Raven's Progressive Matrices Test to measure participants' fluid intelligence through non-verbal, analytical skills and a spatial compatibility test in each condition, as the scenarios are meant to evoke thoughts of financial concern. The second study will observe the cognitive capacities of Qualtrics participants before and after they are paid, to mimic the study of farmers. The target population will be people who are paid at the end or beginning of each month, as finances can impede cognitive function when unforeseen financial situations occur, rent is due, etc. We will also use Raven's matrices to test and a spatial compatibility test to measure the participants' cognitive function before and after they receive their natural income. 


Challenges that may arise include ineffectiveness of hypothetical scenarios as they may not trigger financial concerns for low-income participants because the scenarios are not real. As for the second study, we might not be able to measure the cognition of farmers before and after harvesting season, but instead measure that of those who are paid in a shorter period of time (monthly). Cognition measures may be inaccurate due to external factors such as mental health, familial issues, and more, but may be excluded due to random assignment. 


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
